version: "3.8"
services:
  web:
    container_name: web
    build: .
    command: php -S 0.0.0.0:8000 -t /var/www/html/public
    volumes:
      - ../:/var/www/html
    ports:
      - 3000:8000
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../database/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  